### ISSUE TITLE
module chat

### ISSUE THREAD

**Issue by radiomala** [ychoucha/HUMHUB-module-chat#2]
I download HUMHUB-module-chat master and upload to the server / protected / modules but can not see him in the administration menu modules, please help me!

**Comment by michaelscheurer** [comment]
The same here. Do you still develop this module?

**Comment by petrk94** [comment]
Same issue, @ychoucha are you still developing it?
If not please close it and dont let us try to install something what is not longer working ;)

**Comment by ychoucha** [comment]
Hello sory, the module is not under dev.
i strop it.

The code is still here, if someone want to get it.

sorry
